name: Build & Release Android
on:
    release:
      types: [published]

jobs:
  build_app:
    needs: [check_unit_test]
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
          with:
            java-version: 1.8
      - name: Install FirebaseCLI
        run: npm install -g firebase-tools
      - name: decode google-service.json
        env:
          GOOGLE_SERVICE_ANDROID_DEV: ${{ secrets.GOOGLE_SERVICE_ANDROID_DEV }}
        run: echo $GOOGLE_SERVICE_ANDROID_DEV > ./android/app/google-services.json
      - name: Make gradlew executable
        run: chmod +x ./android/gradlew
      - name: Build Debug APK
        run: fastlane buildApp
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  beta_apk:
    name: Upload
    needs: [build_app]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install Dependencies
        run: gem install bundler && bundle install
      - uses: actions/download-artifact@v2
        with:
          name: android-apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.ANDROID_ID_FIREBASE_DEV }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: team-ci
          file: ./build/app/outputs/apk/develop/release/app-develop-release.apk
      - name: Push ChatWork
        run: fastlane pushChatWork room_id:"193066762" token:${{ secrets.CHATWORK_API_TOKEN }}
